### ISSUE TITLE
ENV Variable to disable logging

### ISSUE THREAD

**Issue by FliKites** [satishweb/docker-doh#14]
I'd like to be able to disable logging. Is their way to do that currently?

**Comment by satishweb** [comment]
doh-server logging?

**Comment by FliKites** [comment]
Yes ---- On Fri, 27 Jan 2023 01:00:21 -0500  ***@***.***  wrote ----
doh-server logging?

**Comment by satishweb** [comment]
You can override the command for the container/pod to send all doh-server output to `/dev/null`.

For example: `docker run -it -e satishweb/doh-server "/server/doh-server -conf /server/doh-server.conf >/dev/null 2>&1"`

**Comment by FliKites** [comment]
Thank you ---- On Fri, 27 Jan 2023 01:21:57 -0500  ***@***.***  wrote ----
You can override the command for the container/pod to send all doh-server output to /dev/null.
For example: docker run -it -e satishweb/doh-server "/server/doh-server -conf /server/doh-server.conf >/dev/null 2>&1"

**Comment by satishweb** [comment]
Glad that I could help :)
