### ISSUE TITLE
Update to 2.3.5

### ISSUE THREAD

**Issue by logopk** [satishweb/docker-doh#15]
Hi,

any chance to get an update to the latest version (v2.3.5)? Please!

https://github.com/m13253/dns-over-https/releases/tag/v2.3.5

Thank you.

Peter

**Comment by satishweb** [comment]
Yes, I will build it on this weekend. Thanks for notifying.

**Comment by logopk** [comment]
Perfect! Really appreciated!

Peter

**Comment by satishweb** [comment]
2.3.5 image is [released](https://hub.docker.com/r/satishweb/doh-server/tags) for all platforms. More details are [here](https://github.com/satishweb/docker-doh/releases/tag/v2.3.5-alpine)
