### ISSUE TITLE
Occasional DNS error from upstream

### ISSUE THREAD

**Issue by pialony** [satishweb/docker-doh#22]
I'm using pihole as an upstream for doh-server.

However, I need to also have a doh server in front of it, and for some reason, that I can't figure out, I'm getting the following occasional errors:
`DNS error from upstream tcp:pihole:53: EOF`

I'm using pihole and doh-server in same docker bridge (single docker compose).
When firefox receives this as dns errors, it caches the response for a few minutes - this means the website I've tried to access when it occurred, would operate partially or not at all.

I've been trying to see if there was any issues with pihole, however if I point firefox directly to it, there is no such issues. I could not find any errors in pihole itself, and the load on the pi zero is very low, so I assume it's not load related.

I've already set the following two env vars:
```
DOH_SERVER_TIMEOUT: "20"
DOH_SERVER_TRIES: "20"
```
But it's not helping.

What more info I can provide to debug and potentially solve this issue?

**Comment by satishweb** [comment]
Hi @pialony,

I can try to help. The DoH server should work with Pi-hole as the upstream DNS. To assist you, could you provide the following?

- DoH Server Logs: Enable debug mode (`DOH_SERVER_VERBOSE=true`) and share the logs.
- Docker Compose File: This will help us identify any configuration issues.
- Firefox DoH Settings: A screenshot of your settings page.
- Network Logs: From Firefox Developer Tools, ensure "Persist Logs" is enabled before accessing the URL.
- Pihole DNS request logs

Note: Please copy only the relevant logs to keep the size smaller.

Thanks,
Satish

**Comment by satishweb** [comment]
Closing the issue, please reopen if you are still facing the same issue.

**Comment by pialony** [comment]
Hey @satishweb , sorry for not replying earlier.
I do not have the option to reopen an issue here, can you please do so?

I already have DOH_SERVER_VERBOSE enabled, and that is the only error log I see when a verbosity is enabled (same as above):
```
2024-12-15T10:23:46.520632983Z 2024/12/15 10:23:46 DNS error from upstream tcp:pihole:53: EOF
```

However, I added `DEBUG: "1"` as well, and it revealed additional logs.
But, I do not think this errors are related, as they are not consecutive to the EOF error, and appear to be of different amount than EOF errors.
I've attached a snippet of the logs as well.

https://gist.github.com/pialony/b0f23ef3e6060421598e54e0194cbc6d

**Comment by satishweb** [comment]
DEBUG variable is for entrypoint script logs.
DOH_SERVER_VERBOSE is for DOH server

I had a look at the logs, it indicates some container networking issues. I do not face these issues on my setup.
