### ISSUE TITLE
Pihole Integration / doh-server Upstream

### ISSUE THREAD

**Issue by Aetherinox** [satishweb/docker-doh#23]
Hey, thanks for providing this.

Quick question as I've looked over the docs, and I see very little (if any) mention of Pihole. So I'm wondering how I can tie Pihole into this.

For a brief rundown, I have the following:
- Pihole server (with DNSSEC)
- x2 instances of Unbound, both Recursive, not Forward)

In my client machine, I set my network adapter up to use my Pihole server IP, I make a request to a website, which Pihole gets, and then grabs the information from the two Unbound instances attached to Pihole.

![2vhN4Ccypt](https://github.com/user-attachments/assets/b2074b1b-19c2-4357-a662-40aba476851e)

But in regards to this doh-server, I'm not sure how it would tie in. It has the env variable for the upstream server

```
upstream = [
    "udp:dns-unbound1:53",
]
```

But that doesn't make a lot of sense to me, because Pihole is the one getting the request when a new domain DNS is queried. So this is the part I'm a little lost on, is what values I should be using.

Pihole doesn't seem to use doh at all when I use unbound as the upstream server. The only time I can see activity is if I change my browser over to specifically use my doh-server for queries by inputting my subdomain assigned to the doh-server such as `https://dns.domain.com/dns-query` and then every time I open a new page in my browser, I see activity in doh-server. But none when I set my client machine to use Pihole.

The only other thing I could think of is setting:
```yml
        environment:
            UPSTREAM_DNS_SERVER: "udp:pihole:53"
```

But I don't seem to get traffic there. I still have a connection, which is weird. But nothing in Pihole is showing as a new query. Yet the doh-server shows queries being made.

```
[22/Nov/2024:08:10:00 +0000] "unagi.amazon.com. IN A"
[22/Nov/2024:08:10:00 +0000] "POST /dns-query HTTP/1.1" 200 77 "" ""
[22/Nov/2024:08:10:02 +0000] "client.wns.windows.com. IN A"
[22/Nov/2024:08:10:02 +0000] "collector.github.com. IN A"
```

When I do use `udp:pihole:53` as my upstream for doh-server, and I go to https://one.one.one.one/help/, it stills ays DoH is not enabled. Even though it appears every page I visit in my browser, is being sent to both Pihole, and DoH from what I can see in the logs.

So with Pihole set, it appears everything "should" be working, but the website test says it's not enabled.

But if I manually go to my domain `https://dns.domain.com/dns-query` I get an actual response

```json
{"Status":2,"Comment":"Invalid argument value: \"ct\" = \"\""}
```

I can then add a domain such as `https://dns.domain.com/dns-query?name=github.com&record=A`

```json
{
  "Status": 0,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "github.com.",
      "type": 1
    }
  ],
  "Answer": [
    {
      "name": "github.com.",
      "type": 1,
      "TTL": 78,
      "Expires": "Fri, 22 Nov 2024 15:40:24 UTC",
      "data": "140.82.116.4"
    }
  ]
}
```

And when I run the test from the link above, I can see the connection in Pihole, coming from doh:

![lBv4PFKABT](https://github.com/user-attachments/assets/afa06a08-7d59-4ed3-9dc6-7bd5624e2f9b)

I've read that some say to disable DNSSEC, so I disabled it in Pihole, and also commented out the trusted anchor key file in Unbound, then ran a DNSSEC test online, and it said it was disabled. Then ran the Cloudflare DoH test again, and it still says `no`.

The other weird note, if I go into Chrome, edit my browser settings, add a custom DNS over HTTPS url, and enter my URL, Chrome says the link is valid and I can browse the web. If I change the URL a bit to use another valid URL from my domain, but not associated with my DNS DoH service, chrome says it's invalid and internet doesn't work. So obviously it's seeing "something" legit about my DoH server.

---

Second question, if you know. DNS Leak Test has a DoH testing page, which allows you to add your own custom DoH server. But for some reason, it appears to not work with this DoH server. If you want to try with your own install:

- https://dnsleaktest.org/dns-over-https

I'm not sure what it's looking for. I changed my DoH server URL to `https://dns.domain.com/dns-query` and I added that as a custom DoH page for testing, and all I get is `Failed`.

**Comment by Aetherinox** [comment]
Just an update (maybe you know some fix).

I've spent all day messing with this. After going through a lot of google results. I've noticed in Chrome under the "Secure DNS" settings, that if you pick ANYTHING other than Cloudflare, then the test at https://one.one.one.one/help/ always returns DoH as "No".

![nxPkPJS4IM](https://github.com/user-attachments/assets/89bb8768-68e7-48f5-ab68-ff59237f1355)

NextDNS, OpenDNS, all say no. So I'm not getting why. As soon as I select **Cloudflare**, it will say Yes. But that's the only option.

**Comment by satishweb** [comment]
Everything seems to be working as expected. Using Pi-hole as the upstream DNS server for the DoH server makes sense to me.

I believe the diagnostic tool at https://one.one.one.one/help/ is specifically focused on Cloudflare's DNS/DoH servers. This means that the "Using DNS over HTTPS (DoH)" status will always show "No" unless you're using Cloudflare’s DoH servers. In this case, you can safely ignore that, as long as the DoH container is showing DNS traffic from the browser.

Pi-hole should record DNS traffic from the DoH server as well. I’m not sure why it isn’t showing up on your end, especially since the DoH server is resolving DNS queries using Pi-hole as the upstream DNS server.

**Comment by Aetherinox** [comment]
> Pi-hole should record DNS traffic from the DoH server as well. I’m not sure why it isn’t showing up on your end, especially since the DoH server is resolving DNS queries using Pi-hole as the upstream DNS server.

As far as I understand, I am seeing traffic. As an example:

![qyZjEvngqP](https://github.com/user-attachments/assets/23381116-39cb-488a-9e15-d1a412ac0d13)

So I believe that part works, doesn't it?

The Cloudflare test makes more sense, because as I said earlier, I switched over to OpenDNS / Quad9 and the Cloudflare test still says no.

I was just looking for some other test to confirm it was working.

**Comment by satishweb** [comment]
That is right, Cloudflare diagnostic URL for the test is not right. If your query logs in PiHole and DoH shows the expected logs, then you are good.

**Comment by Aetherinox** [comment]
Yeah. I've put my DNS query URL into Chrome and Firefox, and the internet runs fine. As soon as I put a bad URL in, the browser internet goes down, so I assume that's the only real way to test, because the browser does work when I enter the correct URL.

Would have been nice if Cloudflare posted something, I wasted like 8 hours of my life diagnosing the issue on why their test wasn't coming back with any results. I've been messing with my Traefik headers, changing the upstream, checking my firewall, the whole damn server got flipped upside down just for that one stupid test.

But when I take the test out of the equation, Pihole is reporting traffic, and the browsers work when I enable DNS over HTTPS, so I guess it's safe to assume it's working as intended.

The only other thing I can't seem to figure out is there's another test at:
- https://dnsleaktest.org/dns-over-https

But when I add my DNS query URL there, it just says "failed". But for some reason, when I look in Pihole to see if I even received any attempts, it does show I received one from `dns.oszx.co` but it says "Bogus (upstream failed)`.

So I went into the server and ran some dig tests on that domain, and for some reason, only THAT domain `dns.oszx.co` returns SERVFAIL when I try to query it with my DNS server. So I'm not sure what the heck is up. Every other domain I try works.

**Comment by satishweb** [comment]
I would just take the DoH and PiHole logs as fact for confirming that everything is working as expected. I wouldn't rely on external diagnostic tools unless it is not a black box to me.

**Comment by Aetherinox** [comment]
Sure thing, I'll go with it for now. Everything appears to be communicating between Pihole, DoH, and Unbound. So we'll go with this for now.

Appreciate the testing and help. I'm monitoring it as I use the web, and so far, haven't had any issues. 

Thanks again!
