### ISSUE TITLE
Multiple upstream DNS

### ISSUE THREAD

**Issue by Taomyn** [satishweb/docker-doh#24]
I run the docker version, is it possible to specify multiple upstream DNS in case the other(s) cannot be reached?

**Comment by satishweb** [comment]
In your docker compose file, try `UPSTREAM_DNS_SERVER: "['udp:1.1.1.1:53','udp:1.0.0.1:53']"` and let me know if that works

**Comment by Taomyn** [comment]
For docker I use podman (on Fedora) and I create the container by the command-line directly, and I tried the following as a parameter:

`--env UPSTREAM_DNS_SERVER="['udp:192.168.1.11:53','udp:192.168.1.71:53']"`

Normally I just used

`--env UPSTREAM_DNS_SERVER="udp:192.168.1.11:53"`

When it tries to start the container the following is logged

```
| Starting DNS Over HTTP Service 

| ENTRYPOINT: Loading docker secrets if found...

| ENTRYPOINT: app-config was not available, running given parameters or default CMD...

2024/12/17 17:17:59 One of the upstreams has not a (udp|tcp|tcp-tls) prefix e.g. udp:1.1.1.1:53
```

**Comment by satishweb** [comment]
Ahh, I see the problem. I am updating the dockerfile and entry point script to allow multiple upstream DNS servers.

I will create a test image with fixes for you shortly.

**Comment by satishweb** [comment]
@Taomyn Please use the below details to test the multi DNS upstream changes:

Image: `satishweb/doh-server-test:v2.3.7`

Docker run command flag: `--env UPSTREAM_DNS_SERVER="udp:192.168.1.11:53,udp:192.168.1.71:53"`

**Comment by Taomyn** [comment]
@satishweb thanks, I was able to deploy the container and it works like it did before so far, although I need to test with one DNS not working which I can't do tonight but will do it tomorrow.

**Comment by satishweb** [comment]
Please reopen the issue if you still have issues with this. I will merge the PR into main branch and recreate the images with new version

**Comment by Taomyn** [comment]
Apologies, been caught up with testing Windows Server 2025 upgrades - I did notice though that this time my reboots and shutdown of my two DNS servers had no effect this time so I would qualify that as a success. Thank-you for taking the time to fix this.
