### ISSUE TITLE
[Feature Request] How to manually set the certs?

### ISSUE THREAD

**Issue by reserveword** [satishweb/docker-doh#7]
I don't have any domain names for now, so I want to run this doh-server with my own self-signed certs for testing, but I can't find anything like `--cert /path/to/mycert.cert --key /path/to/myprivkey.key`.

**Comment by satishweb** [comment]
One question: What are you using for the HTTP proxy? If you are using traefik proxy (as part of the example in the repo), you could just remove the letsencrypt labels and let traefik create a self-signed certificate for you.

I have never used self-signed certificate for DOH server, so I wonder if the browser can ignore certificate errors.

**Comment by reserveword** [comment]
I found a solution for myself by just using HTTP protocol, so no certificate is needed. As it is never recommended to use this built-in tls, setting certs manually is (likely) not essential.
